name: Coverage

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # - name: Run tests
    #   run: cargo test --verbose
    
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@v2.32.17
      with:
        tool: cargo-llvm-cov

    - name: Generate code coverage
      run: cargo llvm-cov --workspace --all-features --codecov --output-path codecov.json

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        files: codecov.json
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: duke-git/rufl
